name: NoAds lists FTP update
on:
  schedule:
  - cron: '30 10 * * *'

  workflow_dispatch:

jobs:
  noads_lists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Timezone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Rome"

      - name: âŒš Set DateTime
        run: |
          sh ./sh/datetime.sh

      - uses: actions/checkout@v3
        with:
          repository: gioxx/xfiles
          path: './'

      - name: â›” Copy lists from gioxx\xfiles
        run: |
          cp experimental.txt ./lists/experimental.txt
          cp facebook.txt ./lists/facebook.txt
          cp filtri.txt ./lists/filtri.txt
          cp siteblock.txt ./lists/siteblock.txt
          cp upd.txt ./lists/upd.txt
          cp /fritz/fritz_blacklist.txt ./lists/fritz_blacklist.txt
          git config --local user.email "114237374+GWall-bot@users.noreply.github.com"
          git config --local user.name "GWall[bot]"
          git add lists/*
          git commit -m "Aggiornamento liste del $checkwebsite" -a

      - name: ðŸ”Œ Push to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./lists/
